name: Windows Build

on:
  workflow_call:

jobs:
  win-build:
    runs-on: [self-hosted, windows]
    
    strategy:
      fail-fast: false
      matrix:
        build-type: [RelDebug]
      
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
        repository: novusengine/Engine

    - name: Premake
      run: |
        premake5 vs2022

    - name: Build
      run: |
        msbuild /m /p:Configuration=${{ matrix.build-type }} Build/Engine.sln
